In [2]:
import numpy as np

In [3]:
print("Hello Deepak I Love you")

Hello Deepak I Love you


In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [7]:
a=np.array(range(5))

In [8]:
a

array([0, 1, 2, 3, 4])

In [9]:
a=np.arange(6)

In [10]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a.clip(3,4) # (ip_arr, min_val, max_val, op) but here only (min,max)


array([3, 3, 3, 3, 4, 4])

In [12]:
# comapre val<3min then 3 
# and val>4max then 4

In [13]:
a.clip(2,4)

array([2, 2, 2, 3, 4, 4])

In [18]:
a2=np.arange(15) 

In [19]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a3 = a2.clip(2,11)

In [22]:
a3

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 11, 11])

In [28]:
a

array([0, 1, 2, 3, 4, 5])

In [53]:
# a_min and a_max is keyword argument =a

In [54]:
b=np.clip(a,a_min=[3,3,4,5,6,6],a_max=5) # here mam and my o\p not match
# mam array show array([3, 3, 4, 6, 6, 6]) theory also but my o/p given wrong???

In [55]:
b

array([3, 3, 4, 5, 5, 5])

In [56]:
b1 = np.clip(a, a_min=[1,2,3,4,1,2], a_max=4)

In [57]:
b1

array([1, 2, 3, 4, 4, 4])

In [58]:
b2 = np.clip(a, a_min=[2,1,2,5,9,11], a_max=4)

In [59]:
b2

array([2, 1, 2, 4, 4, 4])

In [60]:
 b3 = np.clip(a, a_min=[2,3,1,7,8,9], a_max=10)

In [61]:
b3

array([2, 3, 2, 7, 8, 9])

In [62]:
b4 = np.clip(a, a_min=[2,3,1,7,8,9], a_max=3)
b4

array([2, 3, 2, 3, 3, 3])

In [63]:
k=np.arange(8)

In [64]:
k

array([0, 1, 2, 3, 4, 5, 6, 7])

In [66]:
k2=np.clip(k, a_min=[2,3,1,2,6,7,2,9], a_max=5)

In [67]:
k2

array([2, 3, 2, 3, 5, 5, 5, 5])

In [68]:
k3=np.clip(k, a_min=[2,3,1,2,6,7,2,9], a_max=7)
k3

array([2, 3, 2, 3, 6, 7, 6, 7])