In [2]:
import numpy as np

In [3]:
np.version.full_version

'1.18.5'

In [4]:
a=np.arange(9).reshape(3,3)

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a1=np.arange(9)

In [7]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
b=np.clip(a1,a_min=[3,1,3,7,8,9,12,11,15], a_max=[5])

In [9]:
b

array([3, 1, 3, 5, 5, 5, 5, 5, 5])

In [10]:
q3 = np.arange(12).reshape(6,2)

In [11]:
q3.shape

(6, 2)

In [12]:
q3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
q3.shape

(6, 2)

In [14]:
q4=(q3.reshape(2,6))# outer bracket is must
#q3.resize(2,6)

In [15]:
q3.shape

(6, 2)

In [16]:
q4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [17]:
q3.shape

(6, 2)

In [18]:
#np.stack((q4,q3))# ValueError: all input arrays must have the same shape

In [19]:
q=np.arange(12).reshape(2,6)

In [20]:
q

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
np.stack((q4,q))

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]])

In [22]:
np.hstack((q4,q))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

In [23]:
np.vstack((q4,q))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])