In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array([1,2,3],float)
b

array([1., 2., 3.])

In [6]:
c = np.array([2,3,4],str)
c

array(['2', '3', '4'], dtype='<U1')

In [7]:
s = [1,2,3]
s

[1, 2, 3]

In [8]:
a.dtype # what is data type in python for dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
c.dtype # data type UNICODE not ascii 

# unicode is important because evry lang. diff code ex. marathi hindi... 

dtype('<U1')

In [11]:
# s.dtype # error = list list' object has no attribute 'dtype'. so need data type for numpy operations.
type(a) # numpy.ndarray same says for all

numpy.ndarray

In [12]:
type(c)

numpy.ndarray

In [13]:
type(s)
s

[1, 2, 3]

In [14]:
s1 = np.array([[1,2,3],[6,7,8]])
s1

array([[1, 2, 3],
       [6, 7, 8]])

In [15]:
type(s1)

numpy.ndarray

In [33]:
s1.shape # Dimension

(2, 3)

In [35]:
a.shape # np.array give multiple dimensions

(3,)

In [37]:
t = np.array([[[2,3,4]]])
t

array([[[2, 3, 4]]])

In [39]:
t.shape # why o/p this way? refer notebook.

(1, 1, 3)

In [41]:
t1 = np.array([[2,3,4]])
t1.shape

(1, 3)

In [42]:
len(a) # length 3

3

In [46]:
#len(s1) # 2
q = np.array([[1,2,3],[1,2,3],[1,2,3]])
q

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
len(q)

3

In [48]:
2 in q # checking 2 is present in q or not in boleen

True

In [49]:
9 in q

False

In [51]:
f = np.array(range(10),float) # range very good to fill
f

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
f.shape

(10,)

In [53]:
f.reshape((2,5))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [54]:
f.reshape((5,2))

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [18]:
k1 = [4,5,6]
k1[2]

6

In [20]:
k2 = k1 # after you below change in k they automatically backtrace and change the k2 also value
k3 = k1.copy() # if changes in k1 not reflect in k2.
k1

[4, 5, 6]

In [21]:
k2

[4, 5, 6]

In [22]:
k3

[4, 5, 6]

In [23]:
k1[1]=89

In [31]:
k2 # automatically k2 changed
d='deepak'
d


'deepak'

In [26]:
k3 # is copied so not changed

[4, 5, 6]